language: python
python:
  - "3.8"
install:
  - pip install -r reqirements.txt
script:
  - flake8 .
  - sqlite3 app.db < schema.sql
  - coverage run --source api/ -m unittest --verbose tests/test_auth.py && coverage report
